import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type MaintenanceDocument = Maintenance & Document;

export enum MaintenanceStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  COMPLETED = 'COMPLETED',
}

export enum MaintenanceType {
  OIL_CHANGE = 'OIL_CHANGE',
  TIRE_SERVICE = 'TIRE_SERVICE',
  BRAKE_SERVICE = 'BRAKE_SERVICE',
  BATTERY_SERVICE = 'BATTERY_SERVICE',
  ENGINE_SERVICE = 'ENGINE_SERVICE',
  TRANSMISSION_SERVICE = 'TRANSMISSION_SERVICE',
  COOLANT_SERVICE = 'COOLANT_SERVICE',
  AIR_FILTER_REPLACEMENT = 'AIR_FILTER_REPLACEMENT',
  SUSPENSION_SERVICE = 'SUSPENSION_SERVICE',
  BODY_WORK = 'BODY_WORK',
  ELECTRICAL_SERVICE = 'ELECTRICAL_SERVICE',
  GENERAL_INSPECTION = 'GENERAL_INSPECTION',
  PREVENTATIVE_MAINTENANCE = 'PREVENTATIVE_MAINTENANCE',
  REPAIR = 'REPAIR',
  EMERGENCY_REPAIR = 'EMERGENCY_REPAIR',
  WASHING_CLEANING = 'WASHING_CLEANING',
  OTHER = 'OTHER',
}

@Schema({ timestamps: true })
export class Maintenance {
  @Prop({ type: Types.ObjectId, required: true, index: true })
  vehicleId: Types.ObjectId;

  @Prop({ type: Types.ObjectId, required: true })
  agencyId: Types.ObjectId;

  @Prop({ enum: MaintenanceType, required: true })
  maintenanceType: MaintenanceType;

  @Prop({ type: String, default: null })
  description: string;

  @Prop({ required: true })
  odometerAtRequest: number;

  @Prop({ type: Number, default: null })
  estimatedCost: number;

  @Prop({ type: Number, default: null })
  actualCost: number | null;

  @Prop({ enum: MaintenanceStatus, default: MaintenanceStatus.DRAFT })
  status: MaintenanceStatus;

  @Prop({ type: Types.ObjectId, required: true })
  createdBy: Types.ObjectId;

  @Prop({ type: Types.ObjectId, default: null })
  submittedBy: Types.ObjectId | null;

  @Prop({ type: Types.ObjectId, default: null })
  approvedBy: Types.ObjectId | null;

  @Prop({ type: Types.ObjectId, default: null })
  rejectedBy: Types.ObjectId | null;

  @Prop({ type: Types.ObjectId, default: null })
  completedBy: Types.ObjectId | null;

  @Prop({ type: Date, default: null })
  submittedAt: Date | null;

  @Prop({ type: Date, default: null })
  approvedAt: Date | null;

  @Prop({ type: Date, default: null })
  rejectedAt: Date | null;

  @Prop({ type: Date, default: null })
  completedAt: Date | null;

  @Prop({ type: String, default: null })
  workshopName: string | null;

  @Prop({ type: Number, default: null })
  nextServiceDueAtKm: number | null;

  @Prop({ type: Date, default: null })
  scheduledServiceDate: Date | null;

  @Prop({ type: Boolean, default: false })
  autoGenerated: boolean;
}

export const MaintenanceSchema = SchemaFactory.createForClass(Maintenance);

MaintenanceSchema.index({ vehicleId: 1, status: 1 });
MaintenanceSchema.index({ agencyId: 1 });
